#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=01:00:00
#PBS -N app-cortexmap-resample
#PBS -l vmem=20gb
#PBS -V

set -e

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

echo "resampling cortexmap"
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.4.2b ./resample_cortexmap.sh
