#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=1:00:00
#PBS -N app-cortex-mapping
#PBS -l vmem=16gb
#PBS -V

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

if [ ! -f snr.nii.gz ]; then
	echo "computing snr"
	time singularity exec -e docker://brainlife/fsl:5.0.9 ./compute-snr.sh
fi

echo "mapping measures to cortical surface"
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.4.2-freesurfer-update ./cortex-mapping-pipeline.sh

mv *.nii.gz c_ras.mat ./metric/ ./raw/
